# kind-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30080
    hostPort: 8000
  extraMounts:
  - hostPath: /tmp/docker-desktop-root/run/desktop/mnt/host/d/wtf/ml/artifacts
    containerPath: /mnt/artifacts
  - hostPath: /tmp/docker-desktop-root/run/desktop/mnt/host/d/wtf/data/weak_feedback
    containerPath: /mnt/feedback