apiVersion: v1
kind: Service
metadata:
  name: brain-api
  labels:
    app: brain-api
spec:
  selector:
    app: brain-api
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  type: NodePort
